// @ts-check
// node deploy/createBaselineTypesPackages.js 2022 2023 2024 2025
//
// Builds the @baseline-types/dom-<year> npm packages from the Baseline-year
// cuts produced by `npm run baseline-years -- <year> ...` (which writes
// baseline-<year>/ at the repo root). Mirrors createTypesPackages.js but emits
// one package per (dom scope, year) instead of the upstream @types/* set.

import fs from "fs";
import { fileURLToPath } from "url";
import semver from "semver";
import pkg from "prettier";
import path from "path";
const { format } = pkg;

// The default set of years to package. Any 4-digit year works as a CLI arg as
// long as baseline-<year>/ exists; e.g. add 2026 once that year has matured.
export const DEFAULT_YEARS = ["2022", "2023", "2024", "2025"];

// Only the DOM (Window) scope is published for now. The worker/worklet scopes
// are generated by the build too, so this list can grow without other changes.
const SCOPES = [{ key: "dom", label: "DOM" }];

/**
 * @param {string[]} years
 * @returns {Array<{name: string, description: string, year: string, scope: string, readme: string, files: Array<{from: string, to: string, index?: boolean, autoImport?: boolean, group?: string}>}>}
 */
export function baselinePackages(years) {
  const packages = [];
  for (const year of years) {
    for (const scope of SCOPES) {
      packages.push({
        name: `@baseline-types/${scope.key}-${year}`,
        description: `${scope.label} types for web APIs that reached Baseline "Newly available" by ${year}`,
        year,
        scope: scope.key,
        readme: "./readmes/baseline-dom.md",
        files: filesForScope(scope.key, year),
      });
    }
  }
  return packages;
}

/**
 * Mirrors the file layout @types/web uses: a top-level index plus the ts5.5 /
 * ts5.6 / ts5.9 downlevel variants, each with iterable/asynciterable auto-imports.
 * @param {string} scope
 * @param {string} year
 */
function filesForScope(scope, year) {
  const base = `../baseline-${year}`;
  /** @type {Array<{dir: string, group?: string}>} */
  const variants = [
    { dir: "" },
    { dir: "ts5.5/", group: "ts5.5" },
    { dir: "ts5.6/", group: "ts5.6" },
    { dir: "ts5.9/", group: "ts5.9" },
  ];
  const files = [];
  for (const { dir, group } of variants) {
    files.push({
      from: `${base}/${dir}${scope}.generated.d.ts`,
      to: `${dir}index.d.ts`,
      index: true,
      group,
    });
    files.push({
      from: `${base}/${dir}${scope}.iterable.generated.d.ts`,
      to: `${dir}iterable.d.ts`,
      autoImport: true,
      group,
    });
    files.push({
      from: `${base}/${dir}${scope}.asynciterable.generated.d.ts`,
      to: `${dir}asynciterable.d.ts`,
      autoImport: true,
      group,
    });
  }
  return files;
}

/** @param {string[]} years */
const go = async (years) => {
  const generatedDir = new URL("generated/", import.meta.url);
  const templateDir = new URL("template/", import.meta.url);

  const packages = baselinePackages(years);

  for (const pkg of packages) {
    // The cut must already exist (run `npm run baseline-years -- <year>` first).
    const firstSource = new URL(pkg.files[0].from, import.meta.url);
    if (!fs.existsSync(firstSource)) {
      throw new Error(
        `Missing ${fileURLToPath(firstSource)}.\n` +
          `Generate it first:  npm run baseline-years -- ${pkg.year}`,
      );
    }

    const folderName = pkg.name.replace("@", "").replace("/", "-");
    const packagePath = new URL(`${folderName}/`, generatedDir);

    if (fs.existsSync(packagePath)) {
      await fs.promises.rm(packagePath, { recursive: true });
    }
    fs.mkdirSync(packagePath, { recursive: true });

    // Migrate in the template files (package.json, LICENSE, ...).
    for (const templateFile of fs.readdirSync(templateDir)) {
      if (templateFile.startsWith(".")) {
        continue;
      }
      const templatedFile = new URL(templateFile, templateDir);
      fs.copyFileSync(templatedFile, new URL(templateFile, packagePath));
    }

    // Copy the generated .d.ts files into place.
    pkg.files.forEach((fileRef) => {
      const from = new URL(fileRef.from, import.meta.url);
      const to = new URL(fileRef.to, packagePath);
      fs.mkdirSync(new URL(".", to), { recursive: true });
      fs.copyFileSync(from, to);
    });

    prependAutoImports(pkg, packagePath);

    const newPkgJSON = await updatePackageJSON(pkg, packagePath);
    copyREADME(pkg, newPkgJSON, new URL("README.md", packagePath));

    console.log("Built:", pkg.name, `(v${newPkgJSON.version})`);
  }
};

/**
 * @param {ReturnType<typeof baselinePackages>[number]} pkg
 * @param {URL} packagePath
 */
async function updatePackageJSON(pkg, packagePath) {
  const pkgJSONPath = new URL("package.json", packagePath);
  const packageText = fs.readFileSync(pkgJSONPath, "utf8");
  const packageJSON = JSON.parse(packageText);
  packageJSON.name = pkg.name;
  packageJSON.description = pkg.description;
  packageJSON.repository = {
    type: "git",
    url: "https://github.com/uhyo/TypeScript-Baseline-Types.git",
  };
  packageJSON.homepage =
    "https://github.com/uhyo/TypeScript-Baseline-Types#readme";

  // The patch component is the release date (UTC, YYYYMMDD), so every publish is
  // stamped with the day it was cut — e.g. 1.0.20260707. The major and minor stay
  // fixed at 1.0; the date-based patch monotonically increases across releases.
  packageJSON.version = await datedVersion(packageJSON.name);

  fs.writeFileSync(
    pkgJSONPath,
    await format(JSON.stringify(packageJSON), {
      filepath: fileURLToPath(pkgJSONPath),
    }),
  );

  return packageJSON;
}

/**
 * The version for today's release: `1.0.<YYYYMMDD>` (UTC), e.g. `1.0.20260707`.
 *
 * Guards against a same-day double publish: npm rejects re-publishing an
 * existing version, so if the dated version is not strictly greater than what is
 * already on npm (i.e. another release already went out today), the patch is
 * bumped one past the latest instead — a second same-day cut becomes
 * `1.0.20260708`. The once-a-day common case keeps the plain dated version.
 * @param {string} name
 * @returns {Promise<string>}
 */
async function datedVersion(name) {
  const version = `1.0.${releaseDatePatch()}`;
  try {
    const npmResponse = await fetch(`https://registry.npmjs.org/${name}`);
    const latest = (await npmResponse.json())?.["dist-tags"]?.latest;
    // Only bump when today's dated version wouldn't be a strict increase, i.e. a
    // release already happened today (or the patch has drifted ahead of the date
    // from a prior same-day burst).
    if (typeof latest === "string" && !semver.gt(version, latest)) {
      const [major, minor, patch] = latest.split(".");
      return `${major}.${minor}.${Number(patch) + 1}`;
    }
  } catch {
    // NOOP: package not published yet — the dated version is the first release.
  }
  return version;
}

/**
 * The release date as a YYYYMMDD patch component (UTC), e.g. "20260707". Used as
 * the patch segment of the package version so each release is dated.
 * @returns {string}
 */
function releaseDatePatch() {
  const now = new Date();
  const yyyy = now.getUTCFullYear();
  const mm = String(now.getUTCMonth() + 1).padStart(2, "0");
  const dd = String(now.getUTCDate()).padStart(2, "0");
  return `${yyyy}${mm}${dd}`;
}

/**
 * @param {ReturnType<typeof baselinePackages>[number]} pkg
 * @param {{name: string, version: string}} pkgJSON
 * @param {URL} writePath
 */
function copyREADME(pkg, pkgJSON, writePath) {
  let readme = fs.readFileSync(new URL(pkg.readme, import.meta.url), "utf-8");

  const htmlEncodedTag =
    encodeURIComponent(pkgJSON.name) + "%40" + pkgJSON.version;

  readme = readme
    .replace(/\{\{year\}\}/g, pkg.year)
    .replace(/\{\{version\}\}/g, pkgJSON.version)
    .replace(
      /\{\{release_href\}\}/g,
      `https://github.com/uhyo/TypeScript-Baseline-Types/releases/tag/${htmlEncodedTag}`,
    );

  fs.writeFileSync(writePath, readme);
}

/**
 * Appends any files marked as autoImport in the metadata.
 * @param {ReturnType<typeof baselinePackages>[number]} pkg
 * @param {URL} packagePath
 */
function prependAutoImports(pkg, packagePath) {
  /** @type {Map<string | undefined, typeof pkg.files[number][]>} */
  const groups = new Map();
  for (const file of pkg.files) {
    let files = groups.get(file.group);
    if (!files) {
      groups.set(file.group, (files = []));
    }
    files.push(file);
  }
  for (const files of groups.values()) {
    const indexFile = files.find((file) => file.index);
    if (!indexFile) {
      continue;
    }
    const index = new URL(indexFile.to, packagePath);
    if (!fs.existsSync(index)) {
      continue;
    }
    const toPrepend = files
      .filter((f) => !!f.autoImport)
      .map((f) => relativeUrl(index, new URL(f.to, packagePath)))
      .map((f) => `/// <reference path="${f}" />`)
      .join("\n");

    if (toPrepend) {
      const indexText = fs.readFileSync(index, "utf-8");
      fs.writeFileSync(index, `${toPrepend}\n\n${indexText}`);
    }
  }
}

/**
 * @param {URL} from
 * @param {URL} to
 */
function relativeUrl(from, to) {
  if (from.origin !== to.origin) {
    return to.toString();
  }
  if (!from.pathname.endsWith("/")) {
    from = new URL("./", from);
  }
  const relative = path.posix.relative(from.pathname, to.pathname);
  return path.isAbsolute(relative) ||
    relative.startsWith("../") ||
    relative.startsWith("./")
    ? relative
    : `./${relative}`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const years = process.argv.slice(2);
  await go(years.length ? years : DEFAULT_YEARS);
}
